version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # 데이터를 Docker Volume에 저장
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    env_file:
        - .env

  frontend:
    container_name: frontend
    image: 536697226608.dkr.ecr.ap-northeast-2.amazonaws.com/postdm/frontend-app
    ports:
      - "3000:3000"
    restart: always

  backend:
    container_name: backend
    image: 536697226608.dkr.ecr.ap-northeast-2.amazonaws.com/postdm/backend-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always

volumes:
  mysql_data:  # 데이터 영구 저장 Docker Volume